export default function About() {
  return (
    <div className="flex flex-col space-y-10">
      <div className="max-w-6xl text-center flex flex-col justify-center align-middle m-auto p-8 bg-gradient-to-bl from-zinc-900 to-zinc-950 rounded-xl">
        <h1 className="text-6xl font-bold m-4">What is IB Productive?</h1>
        <p className="text-xl m-4">
          IB Productive is an app made with NextJS, tailwind (we try), React,
          Typescript, luck, pain, and effort. Jokes aside however, we create
          tools for IB students (mainly at Allen High School) to manage their
          workload and tasks.
          <br />
          We're IB students at Allen High School. This project began with Xavier
          and Julian (the two best developers of all time totally). The code is
          totally *not* messy at all and does not look like it was generated by
          IB students with low sleep.
        </p>
      </div>

      <div className="max-w-6xl text-center flex flex-col justify-center align-middle m-auto p-8 bg-gradient-to-bl from-zinc-900 to-zinc-950 rounded-xl">
        <h1 className="text-6xl font-bold m-4">Who is IB Productive For?</h1>
        <p className="text-xl m-4">
          Right now it's only accessible to Allen High School students. If you
          would like this application to be available at your school, please
          contact us!
        </p>
      </div>
      <div className="max-w-6xl text-center flex flex-col justify-center align-middle m-auto p-8 bg-gradient-to-bl from-zinc-900 to-zinc-950 rounded-xl">
        <h1 className="text-6xl font-bold m-4">When is IB productive?</h1>
        <p className="text-xl m-4">Idk man, I think you decide that</p>
      </div>
    </div>
  );
}
